/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Clément Fromentin (https://sketchfab.com/Majest)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/sea-life-challenge-pack-0f2db5f8bf9f4212a7fe095594710347
title: Sea life challenge pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-24.51, 47.05, -16.14]} rotation={[-Math.PI / 2, 0, 1.77]}>
            <mesh geometry={nodes['Cylinder016_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[-48.86, 101.03, 128.35]} rotation={[-0.63, -0.64, -0.57]} scale={1.51}>
            <group position={[59.73, 15.6, 3.1]}>
              <mesh geometry={nodes['totem_ailes_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
            </group>
          </group>
          <group position={[139.34, 114.51, -56.51]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={1.52}>
            <group position={[-2.41, -0.69, -4.97]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes['Box009_04_-_Default_0'].geometry}
                material={nodes['Box009_04_-_Default_0'].material}
              />
            </group>
          </group>
          <group position={[131.69, 226.39, -65.64]} rotation={[0, -1.13, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <group position={[-95.1, -572.06, 21.5]}>
              <mesh
                geometry={nodes['UNwrap004_10_-_Default_0'].geometry}
                material={nodes['UNwrap004_10_-_Default_0'].material}
              />
            </group>
          </group>
          <group position={[142.3, 314.56, -47.44]} rotation={[0, -1.13, -Math.PI / 2]} scale={[-1.52, 1.52, 1.52]}>
            <group position={[-95.1, -572.06, 21.5]}>
              <mesh
                geometry={nodes['UNwrap005_10_-_Default_0'].geometry}
                material={nodes['UNwrap005_10_-_Default_0'].material}
              />
            </group>
          </group>
          <group position={[135, 402.18, -67.26]} rotation={[0, -1.13, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <group position={[-95.1, -572.06, 21.5]}>
              <mesh
                geometry={nodes['UNwrap006_10_-_Default_0'].geometry}
                material={nodes['UNwrap006_10_-_Default_0'].material}
              />
            </group>
          </group>
          <group position={[167.76, 30.73, 167.46]} rotation={[-1.71, -0.12, -0.01]} scale={[0.67, 0.67, 0.67]}>
            <mesh geometry={nodes['Cylinder017_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
          </group>
          <group position={[-54.63, 200.35, -239.22]} rotation={[-Math.PI / 2, 0, 0]} scale={6.83}>
            <group position={[-0.89, 0, -1.13]}>
              <mesh geometry={nodes['rock_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
            </group>
          </group>
          <group position={[289.42, 294.19, -170.66]} rotation={[0, 0, 0]} scale={0.27}>
            <mesh geometry={nodes['bulle_22_-_Default_0'].geometry} material={materials['22_-_Default']} />
          </group>
          <group position={[-168.35, 416.37, -205.33]} rotation={[0.14, -0.69, 0.21]} scale={[1, 1, 1]}>
            <group position={[257.02, 20.25, 0]}>
              <mesh geometry={nodes['Line016_20_-_Default_0'].geometry} material={materials['20_-_Default']} />
            </group>
          </group>
          <group position={[-9.44, 412.96, -164.72]} rotation={[0, -0.09, 0]} scale={[1, 1, 1]}>
            <group position={[257.02, 20.25, 0]}>
              <mesh geometry={nodes['Line017_20_-_Default_0'].geometry} material={materials['20_-_Default_0']} />
            </group>
          </group>
          <group position={[-93.68, 436.72, -208.74]} rotation={[0, 1.08, 0]} scale={1}>
            <group position={[83.97, 8.39, 0]}>
              <mesh geometry={nodes['Object031_18_-_Default_0'].geometry} material={materials['18_-_Default']} />
            </group>
          </group>
          <group position={[-92.29, 442.68, -273.81]} rotation={[Math.PI, -1.15, Math.PI]} scale={[1, 1, 1]}>
            <group position={[-209.09, -14.27, 0]}>
              <mesh geometry={nodes['Object035_20_-_Default_0'].geometry} material={materials['20_-_Default_1']} />
            </group>
          </group>
          <group position={[159.01, 226.34, -214.5]} rotation={[0, 1.44, 0]} scale={[1, 1, 1]}>
            <group position={[-51.27, 18.35, 0]}>
              <mesh geometry={nodes['Object039_18_-_Default_0'].geometry} material={materials['18_-_Default_0']} />
            </group>
          </group>
          <group position={[-336.52, 224.19, -154.46]} rotation={[Math.PI, 0.42, -Math.PI]} scale={[1, 1, 1]}>
            <group position={[114.84, 4.19, 0]}>
              <mesh geometry={nodes['Object041_18_-_Default_0'].geometry} material={materials['18_-_Default_1']} />
            </group>
          </group>
          <group position={[-179.18, 60.04, 334.85]} rotation={[0, 0.35, 0]}>
            <group position={[114.84, 4.19, 0]}>
              <mesh geometry={nodes['Object042_19_-_Default_0'].geometry} material={materials['19_-_Default']} />
            </group>
          </group>
          <group position={[-352.89, 99.92, 42.67]} rotation={[0, -1.09, 0]} scale={[1, 1, 1]}>
            <group position={[-209.09, -14.27, 0]}>
              <mesh geometry={nodes['Object043_19_-_Default_0'].geometry} material={materials['19_-_Default_0']} />
            </group>
          </group>
          <group position={[7.78, 135.64, 9.71]} rotation={[-Math.PI / 2, 0, 0]} scale={8.05}>
            <mesh
              geometry={nodes['Line020_09_-_Default_0'].geometry}
              material={nodes['Line020_09_-_Default_0'].material}
            />
            <mesh geometry={nodes['Line020_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
          </group>
          <group position={[55.03, 223.35, -29.1]} rotation={[Math.PI, -0.04, Math.PI / 2]} scale={[0.93, 0.93, 0.93]}>
            <mesh
              geometry={nodes['Box019_15_-_Default_0'].geometry}
              material={nodes['Box019_15_-_Default_0'].material}
            />
          </group>
          <group position={[52.27, 242.7, -4.32]} rotation={[-Math.PI / 2, 0, 0.13]} scale={[0.35, 0.35, 0.91]}>
            <group position={[-2.63, 5.32, -10.86]}>
              <mesh geometry={nodes['Cylinder021_12_-_Default_0'].geometry} material={materials['12_-_Default']} />
            </group>
          </group>
          <group position={[87.29, 48.3, 299.75]} rotation={[-1.49, 0.27, 0.56]} scale={[0.32, 0.32, 0.32]}>
            <group position={[-10.67, 107.49, -100.77]} rotation={[0, 0, 1.58]}>
              <mesh geometry={nodes['dfdf001_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
              <mesh
                geometry={nodes['dfdf001_09_-_Default_0'].geometry}
                material={nodes['dfdf001_09_-_Default_0'].material}
              />
            </group>
          </group>
          <group position={[-21, 246.93, 32.41]} rotation={[Math.PI, -0.88, Math.PI]} scale={[1, 1, 1]}>
            <group position={[257.02, 20.25, 0]}>
              <mesh geometry={nodes['Line021_18_-_Default_0'].geometry} material={materials['18_-_Default_2']} />
            </group>
          </group>
          <group position={[-177.67, 94.97, -18.9]} rotation={[0, 0.66, 0]} scale={[1, 1, 1]}>
            <group position={[-244.75, 1.31, 0]}>
              <mesh geometry={nodes['Object047_20_-_Default_0'].geometry} material={materials['20_-_Default_2']} />
            </group>
          </group>
          <group
            position={[-161.9, 241.81, 257.11]}
            rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
            scale={[1.69, 1.04, 1.69]}>
            <mesh
              geometry={nodes['Cylinder022_17_-_Default_0'].geometry}
              material={nodes['Cylinder022_17_-_Default_0'].material}
            />
            <mesh
              geometry={nodes['Cylinder022_04_-_Default_0'].geometry}
              material={nodes['Cylinder022_04_-_Default_0'].material}
            />
          </group>
          <group position={[-140.69, 168.46, 244.83]} rotation={[0, Math.PI / 6, -Math.PI / 2]} scale={2.72}>
            <mesh
              geometry={nodes['Line023_09_-_Default_0'].geometry}
              material={nodes['Line023_09_-_Default_0'].material}
            />
          </group>
          <group
            position={[-140.7, 318.28, 244.82]}
            rotation={[0, Math.PI / 6, -Math.PI / 2]}
            scale={[-2.72, 2.72, 2.72]}>
            <mesh
              geometry={nodes['Line024_09_-_Default_0'].geometry}
              material={nodes['Line024_09_-_Default_0'].material}
            />
          </group>
          <group position={[204.47, 115.91, 14.54]} rotation={[-1.32, -0.07, -1.82]} scale={[1.78, 1.78, 1.78]}>
            <group position={[-34.74, -4.11, -20.9]}>
              <mesh geometry={nodes['fd015_24_-_Default_0'].geometry} material={materials['24_-_Default']} />
            </group>
          </group>
          <group position={[274.25, 126.48, 35.47]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
            <group position={[83.97, 8.39, 0]}>
              <mesh geometry={nodes['Object048_20_-_Default_0'].geometry} material={materials['20_-_Default_3']} />
            </group>
          </group>
          <group position={[273.22, 107.34, -13.54]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
            <group position={[-209.09, -14.27, 0]}>
              <mesh geometry={nodes['Object049_18_-_Default_0'].geometry} material={materials['18_-_Default_3']} />
            </group>
          </group>
          <group position={[401.64, 36.99, -77.65]} rotation={[-Math.PI / 2, 0, -0.7]}>
            <group position={[5.07, 0.17, -2.31]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                geometry={nodes['POISSON15_17_-_Default_0'].geometry}
                material={nodes['POISSON15_17_-_Default_0'].material}
              />
              <mesh geometry={nodes['POISSON15_14_-_Default_0'].geometry} material={materials['14_-_Default']} />
              <mesh
                geometry={nodes['POISSON15_09_-_Default_0'].geometry}
                material={nodes['POISSON15_09_-_Default_0'].material}
              />
              <mesh geometry={nodes['POISSON15_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
              <mesh geometry={nodes.POISSON15_poisson_0.geometry} material={materials.poisson} />
            </group>
          </group>
          <group position={[294.95, 53.59, -94.03]} rotation={[-2.1, 1.42, -2.74]} scale={[0.33, 0.33, 0.93]}>
            <group position={[0.25, -134.99, -59.54]}>
              <mesh geometry={nodes['amphore001_23_-_Default_0'].geometry} material={materials['23_-_Default']} />
            </group>
          </group>
          <group position={[-354.83, 66.62, -256.97]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
            <group position={[-209.09, -14.27, 0]}>
              <mesh geometry={nodes['Object062_19_-_Default_0'].geometry} material={materials['19_-_Default_1']} />
            </group>
          </group>
          <group position={[48.2, 41.25, 370.91]} rotation={[0, -0.09, 0]} scale={[1, 1, 1]}>
            <group position={[257.02, 20.25, 0]}>
              <mesh geometry={nodes['Line108_19_-_Default_0'].geometry} material={materials['19_-_Default_2']} />
            </group>
          </group>
          <group position={[138.75, 43.96, 347.05]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
            <group position={[83.97, 8.39, 0]}>
              <mesh geometry={nodes['Object063_18_-_Default_0'].geometry} material={materials['18_-_Default_4']} />
            </group>
          </group>
          <group position={[277.22, 66.93, 132.08]} rotation={[0, Math.PI / 4, 0]}>
            <group position={[114.84, 4.19, 0]}>
              <mesh geometry={nodes['Object064_18_-_Default_0'].geometry} material={materials['18_-_Default_5']} />
            </group>
          </group>
          <group position={[20.09, 46.85, 325.61]} rotation={[0, -0.37, 0]} scale={[1, 1, 1]}>
            <group position={[257.02, 20.25, 0]}>
              <mesh geometry={nodes['Line109_18_-_Default_0'].geometry} material={materials['18_-_Default_6']} />
            </group>
          </group>
          <group position={[-147.35, 51.57, 96.61]} rotation={[-3.07, 0.52, 1.42]} scale={[0.93, 0.93, 0.93]}>
            <mesh
              geometry={nodes['Box020_15_-_Default_0'].geometry}
              material={nodes['Box020_15_-_Default_0'].material}
            />
          </group>
          <group position={[144.65, 71.71, -7.84]} rotation={[-1.78, -0.16, 2.19]} scale={[1.78, 1.78, 1.78]}>
            <group position={[-34.74, -4.11, -20.9]}>
              <mesh geometry={nodes['fd019_24_-_Default_0'].geometry} material={materials['24_-_Default_0']} />
            </group>
          </group>
          <group position={[71.07, 86.95, 28.53]} rotation={[Math.PI, -1.39, Math.PI]} scale={[1, 1, 1]}>
            <group position={[83.97, 8.39, 0]}>
              <mesh geometry={nodes['Object069_19_-_Default_0'].geometry} material={materials['19_-_Default_3']} />
            </group>
          </group>
          <group position={[100.08, 97.68, 180.06]} rotation={[Math.PI, -1.15, Math.PI]} scale={[1, 1, 1]}>
            <group position={[-209.09, -14.27, 0]}>
              <mesh geometry={nodes['Object070_18_-_Default_0'].geometry} material={materials['18_-_Default_7']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
