export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Urls = {
  __typename?: "Urls";
  url?: Maybe<Scalars["String"]>;
  expanded_url?: Maybe<Scalars["String"]>;
  display_url?: Maybe<Scalars["String"]>;
  indices?: Maybe<Array<Maybe<Scalars["Int"]>>>;
};

export type Medium = {
  __typename?: "Medium";
  w?: Maybe<Scalars["Int"]>;
  h?: Maybe<Scalars["Int"]>;
  resize?: Maybe<Scalars["String"]>;
};

export type Large = {
  __typename?: "Large";
  w?: Maybe<Scalars["Int"]>;
  h?: Maybe<Scalars["Int"]>;
  resize?: Maybe<Scalars["String"]>;
};

export type Small = {
  __typename?: "Small";
  w?: Maybe<Scalars["Int"]>;
  h?: Maybe<Scalars["Int"]>;
  resize?: Maybe<Scalars["String"]>;
};

export type Thumb = {
  __typename?: "Thumb";
  w?: Maybe<Scalars["Int"]>;
  h?: Maybe<Scalars["Int"]>;
  resize?: Maybe<Scalars["String"]>;
};

export type Sizes = {
  __typename?: "Sizes";
  medium?: Maybe<Medium>;
  large?: Maybe<Large>;
  small?: Maybe<Small>;
  thumb?: Maybe<Thumb>;
};

export type Media = {
  __typename?: "Media";
  id?: Maybe<Scalars["Int"]>;
  id_str?: Maybe<Scalars["String"]>;
  media_url?: Maybe<Scalars["String"]>;
  media_url_https?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
  display_url?: Maybe<Scalars["String"]>;
  expanded_url?: Maybe<Scalars["String"]>;
  type?: Maybe<Scalars["String"]>;
  sizes?: Maybe<Sizes>;
  indices?: Maybe<Array<Maybe<Scalars["Int"]>>>;
};

export type ExtendedEntities = {
  __typename?: "ExtendedEntities";
  media?: Maybe<Array<Maybe<Media>>>;
};

export type Entities = {
  __typename?: "Entities";
  media?: Maybe<Array<Maybe<Media>>>;
  symbols?: Maybe<Array<Maybe<Scalars["String"]>>>;
  user_mentions?: Maybe<Array<Maybe<Scalars["String"]>>>;
  urls?: Maybe<Array<Maybe<Scalars["String"]>>>;
  hashtags?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type ExtendedTweet = {
  __typename?: "ExtendedTweet";
  full_text?: Maybe<Scalars["String"]>;
  extended_entities?: Maybe<ExtendedEntities>;
  entities?: Maybe<Entities>;
  display_text_range?: Maybe<Array<Maybe<Scalars["Int"]>>>;
};

export type User = {
  __typename?: "User";
  id?: Maybe<Scalars["Int"]>;
  id_str?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  screen_name?: Maybe<Scalars["String"]>;
  location?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  translator_type?: Maybe<Scalars["String"]>;
  protected?: Maybe<Scalars["Boolean"]>;
  verified?: Maybe<Scalars["Boolean"]>;
  followers_count?: Maybe<Scalars["Int"]>;
  friends_count?: Maybe<Scalars["Int"]>;
  listed_count?: Maybe<Scalars["Int"]>;
  favourites_count?: Maybe<Scalars["Int"]>;
  statuses_count?: Maybe<Scalars["Int"]>;
  created_at?: Maybe<Scalars["String"]>;
  utc_offset?: Maybe<Scalars["String"]>;
  time_zone?: Maybe<Scalars["String"]>;
  geo_enabled?: Maybe<Scalars["Boolean"]>;
  lang?: Maybe<Scalars["String"]>;
  contributors_enabled?: Maybe<Scalars["Boolean"]>;
  is_translator?: Maybe<Scalars["Boolean"]>;
  profile_background_color?: Maybe<Scalars["String"]>;
  profile_background_image_url?: Maybe<Scalars["String"]>;
  profile_background_image_url_https?: Maybe<Scalars["String"]>;
  profile_background_tile?: Maybe<Scalars["Boolean"]>;
  profile_link_color?: Maybe<Scalars["String"]>;
  profile_sidebar_border_color?: Maybe<Scalars["String"]>;
  profile_sidebar_fill_color?: Maybe<Scalars["String"]>;
  profile_text_color?: Maybe<Scalars["String"]>;
  profile_use_background_image?: Maybe<Scalars["Boolean"]>;
  profile_image_url?: Maybe<Scalars["String"]>;
  profile_image_url_https?: Maybe<Scalars["String"]>;
  profile_banner_url?: Maybe<Scalars["String"]>;
  default_profile?: Maybe<Scalars["Boolean"]>;
  default_profile_image?: Maybe<Scalars["Boolean"]>;
  following?: Maybe<Scalars["String"]>;
  follow_request_sent?: Maybe<Scalars["String"]>;
  notifications?: Maybe<Scalars["String"]>;
};

export type AutogeneratedMainType = {
  __typename?: "AutogeneratedMainType";
  created_at?: Maybe<Scalars["String"]>;
  id?: Maybe<Scalars["Int"]>;
  id_str?: Maybe<Scalars["String"]>;
  text?: Maybe<Scalars["String"]>;
  source?: Maybe<Scalars["String"]>;
  truncated?: Maybe<Scalars["Boolean"]>;
  in_reply_to_status_id?: Maybe<Scalars["String"]>;
  in_reply_to_status_id_str?: Maybe<Scalars["String"]>;
  in_reply_to_user_id?: Maybe<Scalars["String"]>;
  in_reply_to_user_id_str?: Maybe<Scalars["String"]>;
  in_reply_to_screen_name?: Maybe<Scalars["String"]>;
  geo?: Maybe<Scalars["String"]>;
  coordinates?: Maybe<Scalars["String"]>;
  place?: Maybe<Scalars["String"]>;
  contributors?: Maybe<Scalars["String"]>;
  is_quote_status?: Maybe<Scalars["Boolean"]>;
  quote_count?: Maybe<Scalars["Int"]>;
  reply_count?: Maybe<Scalars["Int"]>;
  retweet_count?: Maybe<Scalars["Int"]>;
  favorite_count?: Maybe<Scalars["Int"]>;
  favorited?: Maybe<Scalars["Boolean"]>;
  retweeted?: Maybe<Scalars["Boolean"]>;
  possibly_sensitive?: Maybe<Scalars["Boolean"]>;
  filter_level?: Maybe<Scalars["String"]>;
  lang?: Maybe<Scalars["String"]>;
  timestamp_ms?: Maybe<Scalars["String"]>;
  entities?: Maybe<Entities>;
  extended_tweet?: Maybe<ExtendedTweet>;
  user?: Maybe<User>;
  display_text_range?: Maybe<Array<Maybe<Scalars["Int"]>>>;
};
